services:
  frontend:
    build:
      context: ./Front/GESCOMPAH
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./Front/GESCOMPAH:/app
      - /app/node_modules
    depends_on:
      - backend
