services:
  frontend:
    build:
      context: ./Front/GESCOMPH
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./Front/GESCOMPH:/app
      - /app/node_modules
    depends_on:
      - backend
